version: "3.7"
services:
    api:
        image: "eusa-members-api"
        ports:
            - "3000:3000"
        volumes:
            - type: bind
              source: ./instance
              target: /workspace/instance

        command: "server.js"
